Iglesia/Core/Controllers/ViewComponents/Layout/ControlSidebarViewComponent.cs
using System;
using System.Diagnostics;
using System.IO;
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class ControlSidebarViewComponent : ViewComponent
    {

        public ControlSidebarViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            if (string.IsNullOrEmpty(ViewBag.PageHelpFileName))
            {
                return View("LayoutControlSidebar", string.Empty);
            }

            ViewBag.PageHelpContainer = LoadData(ViewBag.PageHelpFileName);
            return View("LayoutControlSidebar");
        }

        private string LoadData(string filepath)
        {
            var basePath = Directory.GetCurrentDirectory() + @"\wwwroot\files\";
            var baseExtension = @".html";
            var absoluteFilePath = basePath + filepath + baseExtension;

            string result = string.Empty;
            try
            {
                if (!File.Exists(absoluteFilePath))
                {
                    return string.Empty;
                }

                using (StreamReader sr = new StreamReader(new FileStream(absoluteFilePath, FileMode.Open, FileAccess.Read)))
                {
                    result = sr.ReadToEnd();
                }
            }
            catch (FileNotFoundException fex)
            {
                Debug.Write(fex);
                return string.Empty;
            }
            catch (Exception ex)
            {
                Debug.Write(ex);
                return string.Empty;
            }

            return result;
        }
    }
}

Iglesia/Core/Controllers/ViewComponents/Layout/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class FooterViewComponent : ViewComponent
    {

        public FooterViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            return View("LayoutFooter");
        }
    }
}

Iglesia/Core/Controllers/ViewComponents/Layout/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class HeaderViewComponent : ViewComponent
    {

        public HeaderViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            return View("LayoutHeader");
        }
    }
}

Iglesia/Core/Controllers/ViewComponents/Layout/MenuMessageViewComponent.cs
using System.Collections.Generic;
using Commons.Models;
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class MenuMessageViewComponent : ViewComponent
    {

        public MenuMessageViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            var messages = GetData();
            return View("LayoutMenuMessage", messages);
        }

        private List<Message> GetData()
        {
            var messages = new List<Message>();

            messages.Add(new Message
            {
                Id = 1,
                UserId = "",
                DisplayName = "Support Team",
                AvatarURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRxQ-XnyKmKP11SQacp2IutD8Njt89ze2EIIN9AAtrEP5g83jI",
                ShortDesc = "Why not buy a new awesome theme?",
                TimeSpan = "5 mins",
                URLPath = "#",
            });

            messages.Add(new Message
            {
                Id = 1,
                UserId = "",
                DisplayName = "Ken",
                AvatarURL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRxQ-XnyKmKP11SQacp2IutD8Njt89ze2EIIN9AAtrEP5g83jI",
                ShortDesc = "For approval",
                TimeSpan = "15 mins",
                URLPath = "#",
            });

            return messages;
        }
    }
}

Iglesia/Core/Controllers/ViewComponents/Layout/MenuNotificationViewComponent.cs
using System.Collections.Generic;
using Commons.Models;
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class MenuNotificationViewComponent : ViewComponent
    {

        public MenuNotificationViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            var messages = GetData();
            return View("LayoutMenuNotification", messages);
        }

        private List<Message> GetData()
        {
            var messages = new List<Message>();
            messages.Add(new Message
            {
                Id = 1,
                FontAwesomeIcon = "fa fa-users text-aqua",
                ShortDesc = "5 new members joined today",
                URLPath = "#",
            });

            return messages;
        }
    }
}

Iglesia/Core/Controllers/ViewComponents/Layout/MenuTaskViewComponent.cs
using System.Collections.Generic;
using Commons.Models;
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class MenuTaskViewComponent : ViewComponent
    {

        public MenuTaskViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            var messages = GetData();
            return View("LayoutMenuTask", messages);
        }

        private List<Message> GetData()
        {
            var messages = new List<Message>();
            messages.Add(new Message
            {
                Id = 1,
                ShortDesc = "Design some buttons",
                URLPath = "#",
                Percentage = 20,
            });

            return messages;
        }
    }
}

Iglesia/Core/Controllers/ViewComponents/Layout/MenuUserViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class MenuUserViewComponent : ViewComponent
    {

        public MenuUserViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            return View("LayoutMenuUser");
        }
    }
}

Iglesia/Core/Controllers/ViewComponents/Layout/PageHeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class PageHeaderViewComponent : ViewComponent
    {

        public PageHeaderViewComponent()
        {
        }

        public IViewComponentResult Invoke(string filter)
        {
            return View("LayoutPageHeader");
        }
    }
}

Iglesia/Core/Controllers/ViewComponents/Layout/SidebarViewComponent.cs
using Commons.Extensions;
using Commons.Helpers;
using Commons.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Commons.Controllers.ViewComponents.Layout
{
    public class SidebarViewComponent : ViewComponent
    {
        public SidebarViewComponent()
        {
        }
        public IViewComponentResult Invoke(string filter)
        {
            System.Security.Principal.IPrincipal currentUser = this.User;

            var sidebars = new List<SidebarMenu>();
            sidebars.Add(MenuHelpers.AddHeader("Menú Principal"));
            var procesos = MenuHelpers.AddTree("Datos", "fa fa-cubes");
            var gestion = MenuHelpers.AddTree("Gestion", "fa fa-book");
            var finanzas = MenuHelpers.AddTree("Finanzas", "fa fa-book");
            //var reportes = MenuHelpers.AddTree("Reportes", "fa fa-print");
            //var sesion = MenuHelpers.AddTree("Sesion", "fa fa-gear");
            var seguridad = MenuHelpers.AddTree("Sistema", "fa fa-gear");
      
                procesos.TreeChild = new List<SidebarMenu>()
                    {
                        MenuHelpers.AddModule("Personas", "/Personas/Index", "fa fa-circle-o text-aqua"),
                        MenuHelpers.AddModule("Noticias", "/Noticias/Index", "fa fa-circle-o text-aqua"),
                    };

                gestion.TreeChild = new List<SidebarMenu>()
                    {
                        MenuHelpers.AddModule("Actividades", "/Actividades/Index", "fa fa-circle-o text-yellow"),
                        MenuHelpers.AddModule("Turnos", "/Turnos/Index", "fa fa-circle-o text-aqua")
                    };

                //reportes.TreeChild = new List<SidebarMenu>()
                //    {
                //        MenuHelpers.AddModule("Matrices", "/ReportesMatrices/", "fa fa-circle-o text-red"),
                //        MenuHelpers.AddModule("Diccionarios", "/ReportesDiccionarios/", "fa fa-circle-o text-red"),
                //    };

                //sesion.TreeChild = new List<SidebarMenu>()
                //{
                //    MenuHelpers.AddModule("Registra Usuario", "/Identity/Account/Register", "fa fa-user-secret"),
                //    MenuHelpers.AddModule("Cierra Sesion", "/Identity/Account/Logout", "fa fa-sign-out"),
                //};
            // Finanzas
            finanzas.TreeChild = new List<SidebarMenu>();
                finanzas.TreeChild.Add(MenuHelpers.AddModule("Compras", "/Admin/Usuario", "fa fa-circle-o text-green"));
                finanzas.TreeChild.Add(MenuHelpers.AddModule("Gastos mensuales", "/SecurityRoles", "fa fa-circle-o text-green"));
                finanzas.TreeChild.Add(MenuHelpers.AddModule("Ingresos", "/SecurityFunctions", "fa fa-circle-o text-green"));
                finanzas.TreeChild.Add(MenuHelpers.AddModule("Pagos", "/SecurityFunctions", "fa fa-circle-o text-green"));


            // SEGURIDAD
            seguridad.TreeChild = new List<SidebarMenu>();
                    seguridad.TreeChild.Add(MenuHelpers.AddModule("Usuarios", "/Usuario/Index", "fa fa-circle-o text-red"));
                    seguridad.TreeChild.Add(MenuHelpers.AddModule("Roles", "/SecurityRoles", "fa fa-circle-o text-red"));
                    seguridad.TreeChild.Add(MenuHelpers.AddModule("Funciones", "/SecurityFunctions", "fa fa-circle-o text-red"));
           
            sidebars.Add(procesos);
            sidebars.Add(gestion);
            sidebars.Add(finanzas);
            sidebars.Add(seguridad);
            //sidebars.Add(reportes);
            //sidebars.Add(sesion);
            return View("LayoutSidebar", sidebars);

        }
    }
}

Iglesia/Core/Views/Shared/_Layout.cshtml
@{
    var applicationName = "RDV GESTION";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@applicationName - @ViewBag.Title</title>

    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="~/css/select2.min.css" rel="stylesheet" />
    @await Component.InvokeAsync("RegisterCommonsOffline")
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />


    <script src="~/js/select2.full.js"></script>
    @*<link rel="stylesheet" type="text/css" href="~/css/jquery.dataTables.min.css" />*@
    @*<script type="text/javascript" src="~/js/jquery.dataTables.min.js"></script>*@
</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        @await Component.InvokeAsync("Header")
        @await Component.InvokeAsync("Sidebar")
        <div class="content-wrapper">
            <section class="content-header">
                @await Component.InvokeAsync("PageHeader")
                @await Component.InvokeAsync("Breadcrumb")
            </section>
            <section class="content container-fluid">
                @await Component.InvokeAsync("PageAlert")
                <section class="content no-padding">
                    @RenderBody()
                </section>
                @await Component.InvokeAsync(name: "ConfirmModal")
            </section>
        </div>
        @await Component.InvokeAsync("Footer")
        @await Component.InvokeAsync("ControlSidebar")
    </div>
    @RenderSection("Scripts", required: false)   
</body>
</html>

Iglesia/Core/Views/Shared/_LayoutLogin.cshtml
@using Microsoft.AspNetCore.Mvc
@using Newtonsoft.Json
@{
    ViewBag.Title = "Iniciar Sesión";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DGOD - @ViewBag.Title</title>

    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    @await Component.InvokeAsync("RegisterCommonsOffline")

</head>
@*Acá abajo va el wallpaper.*@
<body class="hold-transition login-page" style="background-image: url(/images/background.jpeg);
                                                background-size:     cover;
                                                background-repeat:   no-repeat;
                                                background-position: center center;
                                                height: auto;
                                                ">
    <div class="login-box bg-light-blue-active" style="border-radius: 10px">
        <br />
        <div class="login-logo">
            <a href="/IHome/Index" style="color: white"><b>Iglesia</b> RDV </a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body bg-light-blue-active no-pad-top" style="border-radius: 10px">

            @RenderBody()

        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->

    @RenderSection("scripts", required: false)
</body>
</html>

<!--<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SIBAPIN - ViewBag.Title</title>

    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    await Component.InvokeAsync("RegisterCommonsOffline")

    <link href="~/css/login.css" rel="stylesheet" />

</head>
<body class="hold-transition login-page" style="background-image: url(/images/login.jpg);
                                                background-size:     cover;
                                                background-repeat:   no-repeat;
                                                background-position: center center;
                                                height: auto;
                                                ">
    <div class="login-box bg-info bg-light-blue-active" style="border-radius: 10px">
        <br />
        <div class="login-logo">
            <a href="/Home/Index" style="color: white"><b>SIBAPIN</b></a>
        </div>-->
<!-- /.login-logo -->
<!--<div class="login-box-body bg-light-blue-active no-pad-top" style="border-radius: 10px;">

    RenderBody()

</div>-->
<!-- /.login-box-body -->
<!--</div>-->
<!-- /.login-box -->
<!--RenderSection("scripts", required: false)
</body>
</html>-->