Iglesia/Core/Controllers/Admin/UsuarioController.cs
using Commons.Extensions;
using Commons.Identity.Extensions;
using Commons.Identity.Services;
using Commons.Models;
using Core.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Core.Controllers.Admin
{
    public class UsuarioController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private UserManager<Usuario> _userManager;
        private SignInManager<Usuario> _signIn;
        private UserService<Usuario> _claimsService;

        //public string _Uat { get; }

        public UsuarioController(ApplicationDbContext context, IHttpContextAccessor contextAccessor, UserManager<Usuario> userManager, SignInManager<Usuario> signIn, UserService<Usuario> claimsService, SignInService<Usuario> signService) : base(context, signService, contextAccessor)
        {
            //if (_Uat != null)
            //{                
            _context = context;
            _userManager = userManager;
            _signIn = signIn;
            _claimsService = claimsService;
            //}
            //else
            //{
            //    _signInService.SignOutAsync();
            //}                         
        }



        public IActionResult Index()
        {
            if (((ClaimsPrincipal)User).IsAdmin() || HttpContext.UserHasRoute("/User/index"))
            {
                return View();
            }
            else
            {
                return Redirect("/Identity/Account/AccessDenied"); ;
            }
        }

        public IActionResult _TablaUsuarios(Page<Usuario> pageUser)
        {
            pageUser.SelectPage("/Usuario/_TablaUsuario",
                 _context.Users.Where(x => (x.Persona.Apellido.Contains(pageUser.SearchText)))
                 );

            return PartialView("_TablaUsuarios", pageUser);

        }
    }
}

Iglesia/Core/Views/Usuario/Index.cshtml
@{
    ViewData["Title"] = "Usuarios";
}

<box color="Info">
    <load id="tablaUsuarios" load-url="/Usuario/_TablaUsuarios">
    </load>
</box>

Iglesia/Core/Views/Usuario/_TablaUsuarios.cshtml
@using Commons.Models;
@model Page<Core.Data.Usuario>
<box-header title="Lista de Datos">
    <box-search update-div="tablaUsuario">
        <div class="input-group input-group-sm pull-right" style="max-width: 300px;">
            <a onclick="nuevoUsuario()" class="btn btn-info btn-sm">
                <i class="fa fa-plus"><span class="hidden-xs"> Nuevo</span></i>
            </a>
        </div>
        <div class="input-group input-group-sm pull-right" style="max-width: 300px;">
            <a asp-action="CrearUsuariosPrueba" asp-controller="Usuario" class="btn btn-info btn-sm">
                <i class="fa fa-plus"><span class="hidden-xs"> Crear Usuarios Prueba</span></i>
            </a>
        </div>
    </box-search>
</box-header>
<box-body table="true">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    Codigo
                </th>
                <th>
                    Apellido y Nombre
                </th>
                <th>
                    Nombre de usuario
                </th>
                <th>
                    Correo electronico
                </th>
                <th>
                    Acciones
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Items.OrderBy(x => x.Id).ThenBy(x => x.Persona?.Apellido))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NormalizedUserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NormalizedEmail)
                    </td>
                    <td>

                        <a class="btn btn-primary btn-flat btn-xs" onclick="EditRoles('@item.Id')"><i class="fa fa-file-text-o"></i></a>



                        @*<a onclick="editaDJEstado(@item.Id)" title="Editar" class="btn btn-primary btn-xs"><i class="fa fa-file-text-o"></i></a>*@
                        <!--<a onclick="Eliminar('item.Id')" title="Eliminar" class="btn btn-info btn-xs btn-danger"><i class="fa fa-trash"></i></a>-->
                        @*<a asp-action="Delete"
                               asp-route-id="@item.Id"
                               title="Eliminar"
                               confirm=""
                               confirm-icon="Danger"
                               class="btn btn-danger btn-xs">
                                <i class="fa fa-trash"></i>
                            </a>*@
                    </td>
                </tr>
            }
        </tbody>
    </table>

</box-body>
<box-footer page-update-div="tablaUsuario"></box-footer>
<modal title="Editar roles" function="EditRoles" load-url="@Url.Action("_Assign", "SecurityRoles")"></modal>