Iglesia/Core/Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core.Data;
using Microsoft.AspNetCore.Http;
using Core.Models;
using Core.Services;

namespace Core.Controllers
{
    public class PersonasController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccesor;
        public PersonasController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccesor = httpContextAccessor;
        }

        // GET: Personas
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult _ListadoDePersonas(string Id)
        {
            List<Persona> personas = _context.Persona.ToList();
            //ViewBag.BapinId = Id;
            return PartialView("_ListadoDePersonas", personas);
        }

        // GET: Personas/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Persona
                .FirstOrDefaultAsync(m => m.Id == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        // GET: Personas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Personas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create(Persona persona, IFormFile file)
        {
            ModelState.Remove("Perfil");
            if (ModelState.IsValid)
            {
                persona.Perfil = ImagenService.ConvertirImagen(file);
                _context.Add(persona);
                await _context.SaveChangesAsync();
                AddPageAlerts(PageAlertType.Success, "La persona se creo correctamente .");
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        // GET: Personas/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Persona.FindAsync(id);
            if (persona == null)
            {
                return NotFound();
            }
            return View(persona);
        }

        // POST: Personas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Edit(Persona persona, IFormFile file)
        {
            ModelState.Remove("Perfil");
            if (ModelState.IsValid)
            {
                try
                {
                    persona.Perfil = ImagenService.ConvertirImagen(file);
                    _context.Update(persona);
                    await _context.SaveChangesAsync();
                    AddPageAlerts(PageAlertType.Success, "La persona se modifico correctamente .");
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonaExists(persona.Id))
                    {
                        AddPageAlerts(PageAlertType.Error,"Ocurrio un error al guardar los datos , intentelo nuevamente mas tarde.");
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            return View(persona);
        }

        public IActionResult DetallePersona(string id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var persona = _context.Persona.Find(id);
            return View("DetallePersona", persona);
        }

        public IActionResult VerFotoDePerfil(string Id)
        {
            Persona personaFoto = _context.Persona.Where(x => x.Id == Id).FirstOrDefault();
            if (personaFoto.Perfil != null)
            {
                ViewBag.Imagen = "data:image/jpeg;base64," + Convert.ToBase64String(personaFoto.Perfil);
                ViewBag.Mostrar = true;
                return PartialView("VerFotoDePerfil");
            }
            ViewBag.Mostrar = false;
            return PartialView("VerFotoDePerfil", personaFoto);
        }


        public async Task<IActionResult> DeletePersona(string id)
        {
            if(id == null)
            {
                AddPageAlerts(PageAlertType.Error, "Ha ocurrido un error al borrar la persona , intentelo nuevamente mas tarde .");
                return RedirectToAction(nameof(Index));
            }
            var persona = await _context.Persona.FindAsync(id);
            _context.Persona.Remove(persona);
            await _context.SaveChangesAsync();
            AddPageAlerts(PageAlertType.Success, "La persona se borro correctamente");
            return RedirectToAction(nameof(Index));

        }

        private bool PersonaExists(string id)
        {
            return _context.Persona.Any(e => e.Id == id);
        }
    }
}

Iglesia/Core/Views/Personas/Create.cshtml
@model Core.Data.Persona

@{ 
    ViewData["title"] = "Datos personales";
}

<style>
    .title {
        text-align: center;
        font-size: 25px;
        font-weight: 500;
    }
</style>
<box color="Info">
    <div class="">
        <h2 class="title">Registre sus datos</h2>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Create" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group col-md-4">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Apellido" class="control-label"></label>
                    <input asp-for="Apellido" class="form-control" />
                    <span asp-validation-for="Apellido" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">DNI</label>
                    <input asp-for="Dni" class="form-control" />
                    <span asp-validation-for="Dni" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Edad" class="control-label"></label>
                    <input asp-for="Edad" class="form-control" />
                    <span asp-validation-for="Edad" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Fecha de nacimiento</label>
                    <input asp-for="FechaNacimiento" class="form-control" />
                    <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Teléfono</label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Localidad</label>
                    <input asp-for="Localidad" class="form-control" />
                    <span asp-validation-for="Localidad" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Calle</label>
                    <input asp-for="Calle" class="form-control" />
                    <span asp-validation-for="Calle" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Nro de la Calle</label>
                    <input asp-for="NroCalle" class="form-control" />
                    <span asp-validation-for="NroCalle" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Seleccione una foto de perfil:</label>
                    <input id="archivo" type="file" name="file" />
                    <span id="alerta" class="text-danger"></span>
                </div>
                <hr />
                <div class="col-md-12 ">
                    <div class="form-group pull-right">
                        <input type="submit" value="Guardar" class="btn btn-primary" />
                    </div>
                </div>
            </form>
        </div>
    </div>

</box>
<script>
    $("#CargarArchivo").on("click", function () {
        $("#alerta")[0].innerText = "";
        event.preventDefault();
        let ext = $("#archivo").val().slice(($("#archivo").val().lastIndexOf(".") - 1 >>> 0) + 2);
        if (ext == "jpg") {
            $("#formularioArchivo").submit();
        } else {
            $("#alerta")[0].innerText = "Debe subir un archivo con la extensión JPG.";
        }
    });
</script>

Iglesia/Core/Views/Personas/Delete.cshtml
@model Core.Data.Persona

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Persona</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
     
    
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeletedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeletedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeletedById)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeletedById)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastEditTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastEditTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastEditById)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastEditById)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Display)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Display)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Show)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Show)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Iglesia/Core/Views/Personas/Details.cshtml
@model Core.Data.Persona

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Persona</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dni)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dni)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
 
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeletedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeletedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeletedById)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeletedById)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastEditTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastEditTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastEditById)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastEditById)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Display)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Display)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Show)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Show)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Iglesia/Core/Views/Personas/DetallePersona.cshtml
@model Core.Data.Persona
@using Core.Services
@{
    ViewData["Title"] = "DetallePersona";
}

<div class="row">
    <div class="col-md-4">
        <div class="box box-info">
            <div class="box-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 titulo-detalle"><strong><i class="fa fa-user margin-r-5"></i> Foto de perfil </strong></div>
                        <div class="col-md-12">
                            <p> <img class="profile-user-img img-responsive img-circle" src="@ImagenService.ObtenerImagen(Model.Perfil)" style="width:35%;" alt="Foto de perfil"></p>
                        </div>
                        @*<div class="col-md-8">
                            <div class="row">
                                <div class="col-md-12">
                                    <h4 class="text-center"> @Model.Nombre</h4>
                                </div>
                                <div class="col-md-12 text-center">
                                    <span>DNI - @Model.Dni</span><br>
                                    <span>@Model.FechaNacimiento.ToShortDateString() - @Model.Edad años</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12 text-center">
                                    <h4>Hermano Rios de Vida Claypole</h4>
                                </div>
                            </div>
                        </div>*@
                    </div>
                    <div class="row">
                        <div class="col-md-10"><strong><i class="fa fa-map-marker margin-r-5"></i> Datos personales </strong></div>
                        <div class="col-md-2">
                        </div>
                        <br>
                        <div class="col-md-12">
                            <p class="text-muted">
                            </p><div class="row">
                                <div class="col-md-12">
                                    <span>Nombre y apellido <a class="pull-right">@Model.Nombre  @Model.Apellido</a></span><br>
                                </div>
                                <div class="col-md-12">
                                    <span>Fecha de nacimiento<a class="pull-right">@Model.FechaNacimiento.ToShortDateString()</a></span>
                                </div>
                                <div class="col-md-12">
                                    <span>Edad <a class="pull-right">@Model.Edad</a></span>
                                </div>
                            </div>
                            <p></p>
                        </div>
                    </div>

                    <hr class="separador-detalle">

                    <div class="row">
                        <div class="col-md-8"><strong><i class="fa fa-book margin-r-5"></i>Número de contacto</strong></div>
                        <div class="col-md-4">
                        </div>
                        <br>
                        <div class="col-md-12">
                            <p class="text-muted">
                            </p><div class="row">
                                <div class="col-md-12">
                                    <span>Telefono<a class="pull-right">@Model.Telefono</a></span><br>
                                </div>
                            </div>
                            <p></p>
                        </div>
                    </div>
                    <hr class="separador-detalle">

                    <div class="row">
                        <div class="col-md-10"><strong><i class="fa fa-map-marker margin-r-5"></i> Domicilio </strong></div>
                        <div class="col-md-2">
                        </div>
                        <br>
                        <div class="col-md-12">
                            <p class="text-muted">
                            </p><div class="row">
                                <div class="col-md-12">
                                    <span>Calle y Altura <a class="pull-right">Calle @Model.Calle  @Model.NroCalle</a></span><br>
                                </div>
                                <div class="col-md-12">
                                    <span>Provincia <a class="pull-right">Buenos Aires</a></span>
                                </div>
                                <div class="col-md-12">
                                    <span>Localidad <a class="pull-right">@Model.Localidad</a></span>
                                </div>
                            </div>
                            <p></p>
                        </div>
                    </div>
                    <hr class="separador-detalle">
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="nav-tabs-custom" style="cursor: move;">
            <ul class="nav nav-tabs  ui-sortable-handle">
                @*<li class="" id="pacienteLi"><a href="#Participantes" onclick="OcultarMapa()" data-toggle="tab" aria-expanded="true">Participantes &nbsp; <i class="fa fa-users"></i></a></li>
                    <li class="" id="contactoLi"><a href="#mapaPrueba" onclick="ClickMapa('@Model.Id')" data-toggle="tab" aria-expanded="false">Mapa &nbsp; <i class="fa fa-map"></i></a></li>*@
                <li class="active" id="actividadesLi"><a href="#Actividades" onclick="" data-toggle="tab" aria-expanded="true">Actividades pendientes &nbsp; <i class="fa fa-users"></i></a></li>
                <li class="" id="actividadesHisLi"><a href="#ActividadesHis" onclick="" data-toggle="tab" aria-expanded="true">Actividades históricas &nbsp; <i class="fa fa-users"></i></a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="Actividades" style="position: relative; max-height: 100%;">
                    <load id="_ListadoDeActividades" load-url="/Actividades/_ListadoDeActividades/@Model.Id">
                    </load>
                </div>
                <div class="tab-pane" id="ActividadesHis" style="position: relative; max-height: 100%;">
                    <load id="_ListadoDeActividades" load-url="/Actividades/_ListadoDeActividades/@Model.Id">
                    </load>
                </div>
            </div>
        </div>
    </div>
</div>

Iglesia/Core/Views/Personas/Edit.cshtml
@model Core.Data.Persona

@{
    ViewData["title"] = "Datos personales";
}

<style>
    .title {
        text-align: center;
        font-size: 25px;
        font-weight :500;
    }
</style>

<box color="Warning">
    <div class="">
        <h2 class="title">Modificando datos personales</h2>
    </div>
    <hr/>
    <div class="row">
        <div class="col-sm-12">
            <form method="post" asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group col-md-4">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Apellido" class="control-label"></label>
                    <input asp-for="Apellido" class="form-control" />
                    <span asp-validation-for="Apellido" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">DNI</label>
                    <input asp-for="Dni" class="form-control" />
                    <span asp-validation-for="Dni" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Edad" class="control-label"></label>
                    <input asp-for="Edad" class="form-control" />
                    <span asp-validation-for="Edad" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Fecha de nacimiento</label>
                    <input asp-for="FechaNacimiento" class="form-control" />
                    <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Teléfono</label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Localidad</label>
                    <input asp-for="Localidad" class="form-control" />
                    <span asp-validation-for="Localidad" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Calle</label>
                    <input asp-for="Calle" class="form-control" />
                    <span asp-validation-for="Calle" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Nro de la Calle</label>
                    <input asp-for="NroCalle" class="form-control" />
                    <span asp-validation-for="NroCalle" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Seleccione una foto de perfil:</label>
                    <input id="archivo" type="file" name="file" />
                    <span id="alerta" class="text-danger"></span>
                </div>
                <hr />
                <div class="col-md-12 ">
                    <div class="form-group pull-right">
                        <input type="submit" value="Guardar" class="btn btn-primary" />
                    </div>
                </div>
            </form>
        </div>
    </div>

</box>
<script>
    $("#CargarArchivo").on("click", function () {
        $("#alerta")[0].innerText = "";
        event.preventDefault();
        let ext = $("#archivo").val().slice(($("#archivo").val().lastIndexOf(".") - 1 >>> 0) + 2);
        if (ext == "jpg") {
            $("#formularioArchivo").submit();
        } else {
            $("#alerta")[0].innerText = "Debe subir un archivo con la extensión JPG.";
        }
    });
</script>

Iglesia/Core/Views/Personas/Index.cshtml
@{
    ViewData["Title"] = "Personas RDV";
}

<box>
    <load id="tablaPersonas" load-url="/Personas/_ListadoDePersonas">
    </load>
</box>

Iglesia/Core/Views/Personas/VerFotoDePerfil.cshtml
@model Core.Data.Persona
@if (@ViewBag.Mostrar)
{
    <img src="@ViewBag.Imagen" style="width:100%;height:100%">
}
else
{
    <img src="~/img/UserFondo.jpg" style="width:100%;height:100%">
}

Iglesia/Core/Views/Personas/_ListadoDePersonas.cshtml
@using Commons.Models
@model List<Core.Data.Persona>

<box color="Info">
    <box-header title="Listado de Personas">
        <div class="input-group input-group-sm pull-right" style="max-width: 300px;">
            <a asp-controller="Personas" asp-action="Create" onclick="" class="btn btn-info btn-sm">
                <i class="fa fa-plus"><span class="hidden-xs"> Agregar </span></i>
            </a>
        </div>
    </box-header>
    <box-body table="true" style="padding-inline-start">
        <table id="listadoDePersonas" class="table table-bordered" cellspacing="0" cellpadding="7" width="100%">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>DNI</th>
                    <th>Edad</th>
                    <th>Fecha de nacimiento</th>
                    <th>Telefono</th>
                    <th>Localidad</th>
                    <th>Calle</th>
                    <th>Nro Calle</th>
                    <th>Acciones</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td scope="col">@item.Nombre</td>
                        <td scope="col">@item.Apellido</td>
                        <td scope="col">@item.Dni</td>
                        <td scope="col">@item.Edad</td>
                        <td scope="col">@item.FechaNacimiento.ToShortDateString()</td>
                        <td scope="col">@item.Telefono</td>
                        <td scope="col">@item.Localidad</td>
                        <td scope="col">@item.Calle</td>
                        <td scope="col">@item.NroCalle</td>
                        <td>
                            <a title="ver imagen de perfil" onclick="ImagenPerfil('@item.Id')" class="btn btn-warning btn-xs"><i class="fa fa-image"></i></a>
                            <a title="Detalle Persona" asp-action="DetallePersona" asp-controller="Personas" asp-route-Id="@item.Id" class="btn btn-success btn-xs"><i class="fa fa-user"></i></a>
                            <a asp-action="Edit" asp-controller="Personas" asp-route-Id="@item.Id" title="Modificar Persona" onclick="" class="btn btn-info btn-xs"><i class="fa fa-eye"></i></a>
                            <a asp-action="DeletePersona" asp-controller="Personas" asp-route-id="@item.Id" confirm="¿Está seguro que desea Borrar la persona?" confirm-icon="Success" title='Borrar' data-toggle='tooltip' class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </box-body>
</box>

<modal title="Foto de perfil" callback-modal="true" function="ImagenPerfil" load-url="/Personas/VerFotoDePerfil/" size="Medium"></modal>
<script>
    $(document).ready(function () {
        $('#listadoDePersonas').DataTable({
        "responsive": false,
            columnDefs: [{
                targets: "_all",
                sortable: false
            }],
            "order": [3, 'asc'],
            "language": {
                'url': '@Url.Content("~/lib/arg.json")'
            }
        });
    });

</script>