Iglesia/Core/Controllers/ActividadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core.Data;
using Core.Models;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Core.Controllers
{
    public class ActividadesController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccesor;
        public ActividadesController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccesor = httpContextAccessor;
        }

        #region Actividades

        public async Task<IActionResult> Index()
        {
            return View(await _context.Actividades.ToListAsync());
        }


        public IActionResult _ListadoDeActividades(string Id)
        {
            List<Actividades> actividades = _context.Actividades.ToList();
            //ViewBag.BapinId = Id;
            return PartialView("_ListadoDeActividades", actividades);
        }
        // GET: Actividades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actividades = await _context.Actividades
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actividades == null)
            {
                return NotFound();
            }

            return View(actividades);
        }

        // GET: Actividades/Create
        public IActionResult Create()
        {
            return PartialView();
        }

        // POST: Actividades/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Actividades actividades, string color)
        {
            ModelState.Remove("Id");
            ModelState.Remove("Imagen");
            ModelState.Remove("ListaPersonas");
            if (ModelState.IsValid)
            {
                actividades.Color = color;
                _context.Add(actividades);
                await _context.SaveChangesAsync();
                AddPageAlerts(PageAlertType.Success, "La informacion de la actividad se creo correctamente .");
                return RedirectToAction(nameof(Index));
            }
            AddPageAlerts(PageAlertType.Error, "Ocurrio un error al crear la informacion de la actividad, intente nuevamente .");
            return RedirectToAction(nameof(Index));
        }

        public ActionResult _CargaArchivo(int Id)
        {
            ViewBag.ActividadId = Id;
            return PartialView();
        }
        [HttpPost]
        public async Task<ActionResult> _CargaArchivo(IFormFile file, int  ActividadId)
        {
            try
            {
                if (file == null || file.ContentType != "image/jpeg")
                {
                    AddPageAlerts(PageAlertType.Error, "Debe subir un Icono con la extensión JPG");
                }
                else
                {
                    Actividades actividades = await _context.Actividades.FindAsync(ActividadId);
                    using (var memoryStream = new MemoryStream())
                    {
                        await file.CopyToAsync(memoryStream);
                        actividades.Imagen = memoryStream.ToArray();
                        await _context.SaveChangesAsync();
                    }
                    AddPageAlerts(PageAlertType.Success, $"Se agrego correctamente la imagen de la actividad {actividades.Descripcion} .");
                }
                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception)
            {
                AddPageAlerts(PageAlertType.Error, "Hubo un Error al subir la imagen. Intentelo nuevamente mas tarde.");
                return RedirectToAction("Index");
            }
        }
        public IActionResult ViewFile(int Id)
        {
            Actividades actividades = _context.Actividades.Where(x => x.Id == Id).FirstOrDefault();
            if (actividades.Imagen != null)
            {
                ViewBag.Imagen = "data:image/jpeg;base64," + Convert.ToBase64String(actividades.Imagen);
                return PartialView("VerImagen");
            }
            AddPageAlerts(PageAlertType.Error, "Hubo un Error al ver el archivo PDF. Intentelo nuevamente mas tarde.");
            return RedirectToAction("DetalleComision");
        }
        // GET: Actividades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actividades = await _context.Actividades.FindAsync(id);
            if (actividades == null)
            {
                return NotFound();
            }
            return PartialView(actividades);
        }

        // POST: Actividades/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Actividades actividades, string color)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    actividades.Color = color;
                    _context.Update(actividades);
                    AddPageAlerts(PageAlertType.Success, "La edicion de la informacion de la actividad se guardo correctamente .");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActividadesExists(actividades.Id))
                    {
                        AddPageAlerts(PageAlertType.Error,"Ha ocurrido un error al editar la actividad, intentelo nuevamente.");
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return PartialView(actividades);
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var actividades = await _context.Actividades.FindAsync(id);
                _context.Actividades.Remove(actividades);
                await _context.SaveChangesAsync();
                AddPageAlerts(PageAlertType.Success, "La actividad se borro correctamente .");
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                AddPageAlerts(PageAlertType.Error, "Hubo un error al eliminar la actividad , intentelo nuevamente .");
                return RedirectToAction(nameof(Index));
            }
          
        }

        private bool ActividadesExists(int id)
        {
            return _context.Actividades.Any(e => e.Id == id);
        }

        public IActionResult InformacionActividades(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Actividades actividades = _context.Actividades.Find(id);
            return View(actividades);
        }


        #endregion
    }
}

Iglesia/Core/Controllers/HomeController.cs
using Core.Data;
using Core.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Core.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context) : base(context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            if (!User.Identity.IsAuthenticated){ return Redirect("/Identity/Account/Login"); }
            ViewBag.Actividades = _context.Actividades.Count();
            List <Actividades> actividades = _context.Actividades.ToList();
            return View("Index", actividades);
        }

        public IActionResult FindAllEvents()
        {
            var events = _context.Actividades.Select(x => new
            {
                title = x.Descripcion,
                description = x.Observaciones,
                start = x.FechaInicio.ToString("yyyy/MM/dd"),
                end = x.FechaFinalizado.ToString("yyyy/MM/dd"),
                color = x.Color
            }).ToList();

            return new JsonResult(events);
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Iglesia/Core/Views/Home/Index.cshtml
@using Core.Services
@model List<Core.Models.Actividades>
@{
    ViewData["Title"] = "Home Page";
}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link href="~/fullCalendar/lib/main.css" rel="stylesheet" />


<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>200</h3>

                <p>Personas</p>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
            <div class="inner">
                <h3>@ViewBag.Actividades<sup style="font-size: 20px"></sup></h3>

                <p>Actividades</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>

        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-yellow">
            <div class="inner">
                <h3>0</h3>

                <p>Noticias</p>
            </div>
            <div class="icon">
                <i class="ion ion-person-add"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-red">
            <div class="inner">
                <h3>0</h3>

                <p>Lideres</p>
            </div>
            <div class="icon">
                <i class="ion ion-pie-graph"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>

<!-- Modal -->
<div class="modal fade modal-act" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Listado de actividades</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 id="modalTitle" class="modal-title"></h4>
            </div>
            <div id="modalBody" class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger pull-left" data-dismiss="modal">Cerrar</button>
                <a class="btn btn-primary" onclick="guardarEvento()">Aceptar</a>
            </div>
        </div>
    </div>
</div>

<div class="row">

    <div class="col-md-6 actividades">
        <box color="Warning">
            <div>
                <h3 style="text-align:center;">Lista de Actividades del mes</h3>
            </div>
            <div class="owl-carousel owl-theme custom1" style="padding:0px;margin:0px;">
                @foreach (var item in Model)
                {
                    <div class="item"><img src="@ImagenService.ObtenerImagen(item.Imagen)" alt="Alternate Text" style="width:100%;" /></div>
                }
            </div>
        </box>
    </div>
    <div class="col-md-6">
        <box color="Warning">
            <div class="col-md-12">
                <div id="calendar"></div>
            </div>
        </box>
    </div>

</div>
<script src="https://momentjs.com/downloads/moment.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="~/fullCalendar/lib/main.js"></script>
<script src="~/fullCalendar/lib/locales/es.js"></script>
<script>

    $(function () {
        calendar();
        slider();
    });

    function slider() {
        $('.custom1').owlCarousel({
            animateOut: 'slideOutDown',
            animateIn: 'flipInX',
            items: 1,
            margin: 30,
            stagePadding: 30,
            smartSpeed: 450,
            autoplay: true,
            autoplayTimeout: 1000,
            autoplayHoverPause: true
        });
    }

    function calendar() {

        var events = [];
        $.get("/Home/FindAllEvents", function () {
            alert("success");
        }).done(function (data) {
            var events = [];
            for (var i = 0; i < data.length; i++) {
                events.push({
                    'title': `${data[i].title}`,
                    'start': moment(data[i].start).format("YYYY-MM-DD"),
                    'end': moment(data[i].end).format("YYYY-MM-DD"),
                    'color': `${data[i].color}`,
                    'editable': false
                });
            }

            var calendarEl = document.getElementById('calendar');
            calendar = new FullCalendar.Calendar(calendarEl, {
                locale: 'es',
                headerToolbar: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
                },
                buttonIcons: true,
                /*weekNumbers: true,*/
                navLinks: true, // can click day/week names to navigate views
                editable: true,
                dayMaxEvents: true,
                eventClick: function (event) {
                    $("#modalTitle").html(event.title);
                    $("#modalBody").html(event.description);
                    $("#eventUrl").html(event.url);
                    $("#exampleModal").modal('show');
                    console.log(info.event);
                },
                events: events

            });
            calendar.render();
        });
    }
</script>


@*<script>


                //$.each(data, function (idx,task) {
                //    events.push({
                //        'title': task.title,
                //        'start': task.start,
                //        'end': task.end,
                //        'editable': true
                //    });
                //});
                //for (var i = 0; i < data.length; i++) {
                //    events.push({
                //        'title': data[i].title,
                //        'start': data[i].start,
                //        'end': data[i].end,
                //        'editable': true
                //    });
                //}
                //events.push({
                //    'title': "hola",
                //    'start': "2021-11-09",
                //    'end': "2021-11-10",
                //    'editable': true
                //});
                //alert(data[0].start);
                //console.log(data[0].start);

        //function clickDato() {
        //    alert("prueba");
        //    alert($("#dato").val());
        //}
        var calendar = null;
        var Alleventos = null;


        document.addEventListener('DOMContentLoaded', function () {
            Events();
        });

                                    $(document).



        $(".actividades").show("slow", function () {
            $('.custom1').owlCarousel({
                animateOut: 'slideOutDown',
                animateIn: 'flipInX',
                items: 1,
                margin: 30,
                stagePadding: 30,
                smartSpeed: 450,
                autoplay: true,
                autoplayTimeout: 1000,
                autoplayHoverPause: true
            });
        });

        function Events() {
            $.ajax({
                url: "/Home/FindAllEvents",
                type: "GET",
                success: function (data) {

                    alert("Volvio");
                    var calendarEl = document.getElementById('calendar');
                    calendar = new FullCalendar.Calendar(calendarEl, {
                        locale: 'es',
                        headerToolbar: {
                            left: 'prev,next today',
                            center: 'title',
                            right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
                        },
                        buttonIcons: true,
                        weekNumbers: true,
                        navLinks: true, // can click day/week names to navigate views
                        editable: true,
                        dayMaxEvents: true,
                        eventClick: function (event) {
                            $("#modalTitle").html(event.title);
                            $("#modalBody").html(event.description);
                            $("#eventUrl").html(event.url);
                            $("#exampleModal").modal('show');
                            console.log(info.event);
                        },
                        events: 'https://localhost:44360/Home/FindAllEvents'

                    });
                    calendar.render();
                }
            });
        }

    </script>*@


<!--<div class="row" style="margin-left:10px">
    if (Model.Count > 0)
    {
        <hr />
        <div class="row">
            foreach (var actividad in Model.OrderBy(o => o.Id))
            {
                <div class="col-md-4" style="width:30%;">
                    <div class="box box-primary" style="width:100%;">
                        <div class="box-header with-border">
                            <h3 class="box-title">actividad.Descripcion - Fecha de inicio : actividad.FechaInicio.ToShortDateString()</h3>
                            <span class="label label-primary pull-right"><i class="fa fa-html5"></i></span>
                        </div>-->
<!-- /.box-header -->
<!--<div class="box-body">
    <div>
        <img src="ImagenService.ObtenerImagen(actividad.Imagen)" class="img-thumbnail" style="width:100%;height:80%;" />
    </div>
    <div>
        <h5 class="text-center"></h5>
        <a asp-controller="Actividades" asp-action="InformacionActividades" class="btn btn-success" style="border-radius:2px" asp-route-id="actividad.Id">Mas información</a>
    </div>
</div>-->
<!-- /.box-body -->
<!--</div>--><!-- /.box -->
<!--</div>--><!-- /.col -->
<!--}
        </div>
    }
</div>-->